---
driver:
  name: ec2
  aws_ssh_key_id: kk_aws_kk
  region: us-west-2
  availability_zone: c
  subnet_id: subnet-3773bc6c
  instance_type: t2.micro
  image_id: ami-4836a428
  security_group_ids: sg-7ae3b901
  retryable_tries: 120

provisioner:
  name: chef_solo

platforms:
  - name: centos-7

transport:
  username: ec2-user
  ssh_key: C:\chef-repo\cookbooks\ec2_keys\kk_aws_kk.pem

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[learn_chef_httpd::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
